# Generated by Django 5.0.6 on 2024-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
